### ISSUE TITLE
Crush when using -ev

### ISSUE THREAD

**Issue by WhiteOnBlackCode** [derv82/wifite2#104]
```
[+] (1/1) starting attacks against B4:EE:B4:XX:XX:XX (molly)

 [!] Error: local variable 'attack' referenced before assignment

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 198, in run
 [!]        attack.run()
 [!]    UnboundLocalError: local variable 'attack' referenced before assignment

 [!] Error: local variable 'attack' referenced before assignment

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 47, in main
 [!]        self.run()
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 215, in run
 [!]        if attack.success:
 [!]    UnboundLocalError: local variable 'attack' referenced before assignment

 [!] Exiting
```

**Comment by WhiteOnBlackCode** [comment]
looks like its still WIP
