### ISSUE TITLE
testHandshakePyrit and testHandshakeCowpatty are failing in Debian and Kali

### ISSUE THREAD

**Issue by rhertzog** [derv82/wifite2#105]
With the following versions of pyrit and cowpatty:
$ dpkg-query --show pyrit cowpatty
cowpatty	4.6-1kali3
pyrit	0.4.0-7.1

```
$ ./runtests.sh 
testAnalyze (test_Handshake.TestHandshake) ...  [+]   tshark: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a
 [!]    pyrit: .cap file does not contain a valid handshake
 [!] cowpatty: .cap file does not contain a valid handshake
 [+] aircrack: .cap file contains a valid handshake for A4:2B:8C:16:6B:3A
ok
testHandshakeAircrack (test_Handshake.TestHandshake) ... ok
testHandshakeCowpatty (test_Handshake.TestHandshake) ... FAIL
testHandshakePyrit (test_Handshake.TestHandshake) ... FAIL
testHandshakeTshark (test_Handshake.TestHandshake) ... ok
testTargetClients (test_Target.TestTarget)
Asserts target parsing captures clients properly ... ok
testTargetParsing (test_Target.TestTarget)
Asserts target parsing finds targets ... ok
test_airmon_start (test_Airmon.TestAirmon) ... ok
test_airodump_weird_characters (test_Airodump.TestAirodump) ... ok

======================================================================
FAIL: testHandshakeCowpatty (test_Handshake.TestHandshake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rhertzog/deb/pkg/security/wifite/tests/test_Handshake.py", line 43, in testHandshakeCowpatty
    assert(len(hs.cowpatty_handshakes()) > 0)
AssertionError

======================================================================
FAIL: testHandshakePyrit (test_Handshake.TestHandshake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rhertzog/deb/pkg/security/wifite/tests/test_Handshake.py", line 37, in testHandshakePyrit
    assert(len(hs.pyrit_handshakes()) > 0)
AssertionError

----------------------------------------------------------------------
Ran 9 tests in 3.060s

FAILED (failures=2)
```

**Comment by kimocoder** [comment]
This issue has been resolved :+1: 

`root@kali:~/Desktop/wifite2# ./runtests.sh 
test_airmon_start (test_Airmon.TestAirmon) ... ok
testTargetClients (test_Target.TestTarget)
Asserts target parsing captures clients properly ... ok
testTargetParsing (test_Target.TestTarget)
Asserts target parsing finds targets ... ok
test_airodump_weird_characters (test_Airodump.TestAirodump) ... ok
testAnalyze (test_Handshake.TestHandshake) ...  [+] Discovered essid "Test Router Please Ignore"
 [+]   tshark: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a
 [+]    pyrit: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a (Test Router Please Ignore)
 [+] cowpatty: .cap file contains a valid handshake for (Test Router Please Ignore)
 [+] aircrack: .cap file contains a valid handshake for A4:2B:8C:16:6B:3A
ok
testHandshakeAircrack (test_Handshake.TestHandshake) ... ok
testHandshakeCowpatty (test_Handshake.TestHandshake) ...  [+] Discovered essid "Test Router Please Ignore"
ok
testHandshakePyrit (test_Handshake.TestHandshake) ... ok
testHandshakeTshark (test_Handshake.TestHandshake) ... ok

----------------------------------------------------------------------
Ran 9 tests in 7.769s

OK`

**Comment by ruzlino1ne** [comment]
root@no1ne-ubuntu:~/wifite2# bash runtests.sh 
test_airmon_start (test_Airmon.TestAirmon) ... ok
test_airodump_weird_characters (test_Airodump.TestAirodump) ... ok
testTargetClients (test_Target.TestTarget)
Asserts target parsing captures clients properly ... ok
testTargetParsing (test_Target.TestTarget)
Asserts target parsing finds targets ... ok
testAnalyze (test_Handshake.TestHandshake) ...  [+] Discovered essid "Test Router Please Ignore"
 [+]   tshark: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a
 [+]    pyrit: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a (Test Router Please Ignore)
 [!] cowpatty: .cap file does not contain a valid handshake
 [+] aircrack: .cap file contains a valid handshake for A4:2B:8C:16:6B:3A
ok
testHandshakeAircrack (test_Handshake.TestHandshake) ... ok
testHandshakeCowpatty (test_Handshake.TestHandshake) ...  [+] Discovered essid "Test Router Please Ignore"
FAIL
testHandshakePyrit (test_Handshake.TestHandshake) ... ok
testHandshakeTshark (test_Handshake.TestHandshake) ... ok

======================================================================
FAIL: testHandshakeCowpatty (test_Handshake.TestHandshake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/wifite2/tests/test_Handshake.py", line 47, in testHandshakeCowpatty
    assert(len(hs.cowpatty_handshakes()) > 0)
AssertionError

----------------------------------------------------------------------
Ran 9 tests in 2.912s

Still FAIL "cowpatty" What will i do?

**Comment by ghost** [comment]
sorry bro my board does not go into monitor mode because of this inaccurate

вс, 5 янв. 2020 г. в 21:17, ruzlino1ne <notifications@github.com>:
