### ISSUE TITLE
BUG : Exception: Could not find the mac address for

### ISSUE THREAD

**Issue by TasosR83** [derv82/wifite2#112]
Starting the script with 
sudo ./Wifite.py 
gives the following

  .               .    
.´  ·  .     .  ·  `.  wifite 2.1.6
:  :  :  (¯)  :  :  :  automated wireless auditor
`.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
  `     /¯¯¯\     ´    

 [!] conflicting process: avahi-daemon (PID 13523)
 [!] conflicting process: avahi-daemon (PID 13525)
 [!] if you have problems: kill -9 PID or re-run wifite with --kill)

 [+] looking for wireless interfaces

 [!] Error: Could not find the mac address for 

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/*/APPS/wifite2/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/home/*/APPS/wifite2/wifite/wifite.py", line 46, in main
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/home/*/APPS/wifite2/wifite/config.py", line 121, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/home/*/APPS/wifite2/wifite/tools/airmon.py", line 288, in ask
 [!]        a = Airmon()
 [!]    File "/home/*/APPS/wifite2/wifite/tools/airmon.py", line 69, in __init__
 [!]        self.refresh()
 [!]    File "/home/*/APPS/wifite2/wifite/tools/airmon.py", line 73, in refresh
 [!]        self.interfaces = Airmon.get_interfaces()
 [!]    File "/home/*/APPS/wifite2/wifite/tools/airmon.py", line 104, in get_interfaces
 [!]        interfaces.append(AirmonIface(phy, interface, driver, chipset))
 [!]    File "/home/*/APPS/wifite2/wifite/tools/airmon.py", line 22, in __init__
 [!]        self.mac_address = Ifconfig.get_mac(interface)
 [!]    File "/home/*/APPS/wifite2/wifite/tools/ifconfig.py", line 60, in get_mac
 [!]        raise Exception('Could not find the mac address for %s' % interface)
 [!]  Exception: Could not find the mac address for

 [!] Exiting

NOTE: my username was replaced with *

**Comment by rafacuest** [comment]
Same as me.
My ubuntu box 
Linux v5 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by derv82** [comment]
Seems the script is finding empty interfaces from `airmon-ng`...

What is the output when you run `sudo airmon-ng`?

And `ifconfig` as well...

**Comment by mamilux** [comment]
Same here on nethunter wifite2. 1.6
