### ISSUE TITLE
Exception AttributeError: "'Process' object has no attribute 'pid'"

### ISSUE THREAD

**Issue by strasharo** [derv82/wifite2#120]
I'm trying to run on a recent Arch Linux via  python2:

```
[root@bbbe wifite2]# python2 --version
Python 2.7.15
[root@bbbe wifite2]# python2 ./Wifite.py 
  .               .    
.´  ·  .     .  ·  `.  wifite 2.1.6
:  :  :  (¯)  :  :  :  automated wireless auditor
`.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
  `     /¯¯¯\     ´    


 [+] looking for wireless interfaces
     using interface wlan0mon (already in monitor mode)
     you can specify the wireless interface using -i wlan0

 [+] Scanning. Found 0 target(s), 0 client(s). Ctrl+C when ready                                                                                                                                                                              
 [!] Error: [Errno 2] No such file or directory

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/work/wifite2/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/root/work/wifite2/wifite/wifite.py", line 47, in main
 [!]        self.run()
 [!]    File "/root/work/wifite2/wifite/wifite.py", line 135, in run
 [!]        s = Scanner()
 [!]    File "/root/work/wifite2/wifite/util/scanner.py", line 42, in __init__
 [!]        self.targets = airodump.get_targets()
 [!]    File "/root/work/wifite2/wifite/tools/airodump.py", line 161, in get_targets
 [!]        Wash.check_for_wps_and_update_targets(capfile, targets)
 [!]    File "/root/work/wifite2/wifite/tools/wash.py", line 32, in check_for_wps_and_update_targets
 [!]        p = Process(command)
 [!]    File "/root/work/wifite2/wifite/util/process.py", line 89, in __init__
 [!]        self.pid = Popen(command, stdout=sout, stderr=serr, cwd=cwd, bufsize=bufsize)
 [!]    File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
 [!]        errread, errwrite)
 [!]    File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
 [!]        raise child_exception
 [!]    OSError: [Errno 2] No such file or directory

 [!] Exiting

Exception AttributeError: "'Process' object has no attribute 'pid'" in <bound method Process.__del__ of <wifite.util.process.Process object at 0xb6747ef0>> ignored
Exception AttributeError: "'Process' object has no attribute 'pid'" in <bound method Process.__del__ of <wifite.util.process.Process object at 0xb674f1f0>> ignored
[root@bbbe wifite2]# 
```

**Comment by semeion** [comment]
I am using archlinux here too and seems like wifite doesn´t work anymore...  Do you know the reason?

**Comment by strasharo** [comment]
I'm hitting two issues on Arch currently. This one which appeared recently and is specific to python2 and another one which appears on python3 and was present before:
https://github.com/derv82/wifite2/issues/92

**Comment by derv82** [comment]
I reproduced this using a test in `wifite.util.process` when running Python 2.

Try the latest version (`2.1.7`) and let me know if you still encounter the `Exception AttributeError: "'Process' object` error.

**Comment by strasharo** [comment]
Yep, works fine now, thanks a lot.
