### ISSUE TITLE
Something missed with pmkid?

### ISSUE THREAD

**Issue by avin** [derv82/wifite2#124]
got an error, seems something missed?
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/wifite2/wifite/attack/pmkid.py", line 150, in dumptool_thread
    dumptool = HcxDumpTool(self.target, self.pcapng_file)
  File "/opt/wifite2/wifite/tools/hashcat.py", line 82, in __init__
    self.proc = Process(command)
  File "/opt/wifite2/wifite/util/process.py", line 89, in __init__
    self.pid = Popen(command, stdout=sout, stderr=serr, cwd=cwd, bufsize=bufsize)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by ragefan** [comment]
Hi,
I ve got the same issue 👍 

 [!] Error: [Errno 2] No such file or directory

 [!] Full stack trace below

 [!]    Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/tools/wifite2/wifite/attack/pmkid.py", line 150, in dumptool_thread
    dumptool = HcxDumpTool(self.target, self.pcapng_file)
  File "/root/tools/wifite2/wifite/tools/hashcat.py", line 82, in __init__
    self.proc = Process(command)
  File "/root/tools/wifite2/wifite/util/process.py", line 89, in __init__
    self.pid = Popen(command, stdout=sout, stderr=serr, cwd=cwd, bufsize=bufsize)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
 [!]    File "/root/tools/wifite2/wifite/attack/all.py", line 57, in attack_single
 [!]        result = attack.run()
 [!]    File "/root/tools/wifite2/wifite/attack/pmkid.py", line 70, in run
 [!]        pmkid_file = self.capture_pmkid()
 [!]    File "/root/tools/wifite2/wifite/attack/pmkid.py", line 92, in capture_pmkid
 [!]        pmkid_hash = pcaptool.get_pmkid_hash(self.pcapng_file)
 [!]    File "/root/tools/wifite2/wifite/tools/hashcat.py", line 110, in get_pmkid_hash
 [!]        hcxpcap_proc = Process(command)
 [!]    File "/root/tools/wifite2/wifite/util/process.py", line 89, in __init__
 [!]        self.pid = Popen(command, stdout=sout, stderr=serr, cwd=cwd, bufsize=bufsize)
 [!]    File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
 [!]        errread, errwrite)
 [!]    File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
 [!]        raise child_exception
 [!]    OSError: [Errno 2] No such file or directory

**Comment by derv82** [comment]
Whoops, forgot to test without `hashcat` + `hcxdumptools` + `hcxtools` installed.

In wifite 2.1.8, it will now say:

> Skipping PMKID attack, missing required tools: `hcxdumptool`, `hcxpcaptool`
