### ISSUE TITLE
Crashes if target does not appear / disappears

### ISSUE THREAD

**Issue by derv82** [derv82/wifite2#132]
```
[!] Traceback (most recent call last):
[!] File "/home/asdf/Tools/wifite2/wifite/attack/all.py", line 76, in attack_single
[!] result = attack.run()
[!] File "/home/asdf/Tools/wifite2/wifite/attack/wpa.py", line 42, in run
[!] handshake = self.capture_handshake()
[!] File "/home/asdf/Tools/wifite2/wifite/attack/wpa.py", line 94, in capture_handshake
[!] airodump_target = self.wait_for_target(airodump)
[!] File "/home/asdf/Tools/wifite2/wifite/model/attack.py", line 24, in wait_for_target
[!] raise Exception('Target did not appear after %d seconds, stopping' % Attack.target_wait)
[!] Exception: Target did not appear after 60 seconds, stopping
```

Bad if target goes down, or if goes out of range, what if people are war-walkin'?

**Comment by daxueba** [comment]
wifite2/wifite/model/attack.py 
old：target_wait = 60
new：target_wait = 600

**Comment by Spessmen14** [comment]
Still getting this issue.
