### ISSUE TITLE
Cannot find any interfaces in Mode:Monitor

### ISSUE THREAD

**Issue by elohffa** [derv82/wifite2#142]
Interface   PHY   Driver              Chipset                                                   
-----------------------------------------------------------------------
 1. wlan0       phy0  wl                  Broadcom Limited BCM4331 802.11a/b/g/n (rev 02)
 2. wlan1       phy1  rtl8814au           Realtek Semiconductor Corp.   

 [+] Select wireless interface (1-2): 2
 [+] enabling monitor mode on wlan1... failed
failed

 [!] Error: Cannot find any interfaces in Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/root/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/root/wifite2/wifite/config.py", line 130, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 190, in start
 [!]        raise Exception('Cannot find any interfaces in Mode:Monitor')
 [!]  Exception: Cannot find any interfaces in Mode:Monitor

 [!] Exiting

**Comment by elohffa** [comment]
I  can use the airdump-ng comand to enable my wlan1 to monitor mode

airodump-ng wlan1   
CH  8 ][ Elapsed: 36 s ][ 2018-09-12 13:30 ][ wlan1 reset to monitor mode                                        
                                                                                                                          
 BSSID              PWR  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID
                                                                                                                          
 48:F8:B3:DD:2C:04  -56      267       18    0   3  130  WPA2 CCMP   PSK  sunsunsun                                       
 C2:02:8E:90:45:BD  -84       40        0    0   1  54e. WEP  WEP         <length:  0>                                    
 C6:02:8E:90:45:BD  -86       27        0    0   1  130  WPA2 CCMP   PSK  <length:  0>                                    
 28:6C:07:C1:AF:EE  -87       70        2    0   1  130  WPA2 CCMP   PSK  CHIU’s                                           
                                                                                                                           
 BSSID              STATION            PWR   Rate    Lost    Frames  Probe                                                 
                                                                                                                           
 (not associated)   54:60:09:6D:A4:E0  -87    0 - 1      3        5  Sydney@Home                                           
 (not associated)   40:9B:CD:0F:67:80  -83    0 - 1    118       49  kenho2205                                             
 (not associated)   D0:04:01:A0:F9:06  -83    0 - 1      0        3  indrawati,CMS                                         
 28:6C:07:C1:AF:EE  38:1D:D9:A1:20:39   -1    1e- 0      0        1                                                        
 28:6C:07:C1:AF:EE  70:E7:2C:05:56:00   -1    1e- 0      0        1                                                        

[1]+  Stopped                 airodump-ng wlan1
root@kali:~/wifite2#

**Comment by elohffa** [comment]
I'm using ALFA AWUS1900

**Comment by kimocoder** [comment]
I do too..

"ifconfig wlan1 down"
"iwconfig wlan1 mode monitor"

then run "wifite"

**Comment by pablopunk** [comment]
@elohffa did you solve this?

**Comment by pablopunk** [comment]
This is a duplicate of https://github.com/derv82/wifite2/issues/86

**Comment by p-dot-max** [comment]
I recom. ya to process :- 
sudo ifconfig wlanx down
sudo airmon-ng check kill 
sudo airmon-ng start wlanx

sudo service networking restart 
sudo service NetworkManager restart

:+1:

**Comment by MojoMoe** [comment]
> I recom. ya to process :-
> sudo ifconfig wlanx down
> sudo airmon-ng check kill
> sudo airmon-ng start wlanx
> 
> sudo service networking restart
> sudo service NetworkManager restart
> 
> 👍

This worked for me in Kali 5.9.0-kali5-amd64 
Thanks.
