### ISSUE TITLE
Crash on Fedora

### ISSUE THREAD

**Issue by mrprompt** [derv82/wifite2#155]
Running on Fedora, applications crash in scanner

Output:

```
    Interface   PHY   Driver              Chipset                                                                                                                                              
-----------------------------------------------------------------------
 1. wlp0s20f0u2 phy1  mt7601u             Ralink Technology, Corp. MT7601U
 2. wlp2s0      phy0  ath10k_pci          Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)

 [+] Select wireless interface (1-2): 1
 [+] enabling monitor mode on wlp0s20f0u2... enabled wlp0s20f0u2mon

 [+] Scanning. Found 0 target(s), 0 client(s). Ctrl+C when ready                                                                                                                               
 [!] Error: [Errno 2] No such file or directory

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python2.7/site-packages/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python2.7/site-packages/wifite/__main__.py", line 54, in start
 [!]        self.scan_and_attack()
 [!]    File "/usr/lib/python2.7/site-packages/wifite/__main__.py", line 78, in scan_and_attack
 [!]        s = Scanner()
 [!]    File "/usr/lib/python2.7/site-packages/wifite/util/scanner.py", line 42, in __init__
 [!]        self.targets = airodump.get_targets(old_targets=self.targets)
 [!]    File "/usr/lib/python2.7/site-packages/wifite/tools/airodump.py", line 163, in get_targets
 [!]        Tshark.check_for_wps_and_update_targets(capfile, targets)
 [!]    File "/usr/lib/python2.7/site-packages/wifite/tools/tshark.py", line 177, in check_for_wps_and_update_targets
 [!]        p = Process(command)
 [!]    File "/usr/lib/python2.7/site-packages/wifite/util/process.py", line 89, in __init__
 [!]        self.pid = Popen(command, stdout=sout, stderr=serr, stdin=stdin, cwd=cwd, bufsize=bufsize)
 [!]    File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
 [!]        errread, errwrite)
 [!]    File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
 [!]        raise child_exception
 [!]    OSError: [Errno 2] No such file or directory

 [!] Exiting

 [!] Note: Leaving interface in Monitor Mode!
 [!] To disable Monitor Mode when finished: airmon-ng stop wlp0s20f0u2mon
```

Any idea how can I fix this?

**Comment by mrprompt** [comment]
Fix: install wireshark! :D

**Comment by kimocoder** [comment]
Wait a second.. @derv82 should include a simplier output for the missing dependency instead of showing more a crash

**Comment by mrprompt** [comment]
I should reopen issue ?

**Comment by kimocoder** [comment]
No I tagged him anyway
