### ISSUE TITLE
Crash after Wifite captures a handshake file: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by FaolanKusibo** [derv82/wifite2#180]
Im not sure what happened to cause this error. One day it worked, the next it didnt. No changes, no updated software, no new files. There should be no reason for it,
Full output(minus SSID and BSSD)

 [0:08:20] starting wpa handshake capture on "*********************"
 [0:08:17] new client found: ************************                         
 [0:08:08] sending 5 deauth to ****************...  sent 
 [0:00:12] handshake captured! saved as "hs/************************************.cap"
Traceback (most recent call last):
  File "/usr/bin/wifite", line 3462, in <module>
    engine.Start()
  File "/usr/bin/wifite", line 1391, in Start
    if wpa_attack.RunAttack():
  File "/usr/bin/wifite", line 2077, in RunAttack
    self.wpa_get_handshake()
  File "/usr/bin/wifite", line 2219, in wpa_get_handshake
    if self.RUN_CONFIG.WPA_STRIP_HANDSHAKE: self.strip_handshake(save_as)
  File "/usr/bin/wifite", line 2470, in strip_handshake
    rename(capfile + '.temp', output_file)
  File "/usr/bin/wifite", line 1582, in rename
    os.rename(old, new)
OSError: [Errno 2] No such file or directory

**Comment by RaduNico** [comment]
It looks like you are using wifite1, this is the repository for wifite2. I realize I am not being very helpful, but you might want to use the new version, more than surely this bug is not present.

If you want to keep using wifite1 you might want to post this Issue in [https://github.com/derv82/wifite](url) and hope you get some solution.
