### ISSUE TITLE
F29 start-issue

### ISSUE THREAD

**Issue by ajh34** [derv82/wifite2#204]
Any idea what this error means? I assume it is a missing dependency but I'm not familiar enough with Python to know what it is.

[!] Error: [Errno 2] No such file or directory

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python2.7/site-packages/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python2.7/site-packages/wifite/__main__.py", line 54, in start
 [!]        self.scan_and_attack()
 [!]    File "/usr/lib/python2.7/site-packages/wifite/__main__.py", line 78, in scan_and_attack
 [!]        s = Scanner()
 [!]    File "/usr/lib/python2.7/site-packages/wifite/util/scanner.py", line 42, in __init__
 [!]        self.targets = airodump.get_targets(old_targets=self.targets)
 [!]    File "/usr/lib/python2.7/site-packages/wifite/tools/airodump.py", line 163, in get_targets
 [!]        Tshark.check_for_wps_and_update_targets(capfile, targets)
 [!]    File "/usr/lib/python2.7/site-packages/wifite/tools/tshark.py", line 177, in check_for_wps_and_update_targets
 [!]        p = Process(command)
 [!]    File "/usr/lib/python2.7/site-packages/wifite/util/process.py", line 89, in __init__
 [!]        self.pid = Popen(command, stdout=sout, stderr=serr, stdin=stdin, cwd=cwd, bufsize=bufsize)
 [!]    File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
 [!]        errread, errwrite)
 [!]    File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
 [!]        raise child_exception
 [!]    OSError: [Errno 2] No such file or directory

 [!] Exiting

**Comment by RaduNico** [comment]
The dependency you are missing is tshark. What is odd is that the function 'check_for_wps_and_update_targets' should detect that tshark exists or not on your system and raise a proper error instead of this.

Are you using the latest version of wifite2? Could you provide the output of the command 'which tshark'?
