### ISSUE TITLE
whats the problem??? help me!!! t.t

### ISSUE THREAD

**Issue by 687766616e** [derv82/wifite2#206]
```
huitc@HuiTC716:~/wifite2$ sudo python3 Wifite.py
   .               .
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´

^[[A
 [+] Checking airmon-ng...^[[A
 [!] airmon-ng did not find any wireless interfaces
 [!] Make sure your wireless device is connected
 [!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

 [!] Error: airmon-ng did not find any wireless interfaces

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/huitc/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/home/huitc/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/home/huitc/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/home/huitc/wifite2/wifite/tools/airmon.py", line 299, in ask
 [!]        raise Exception('airmon-ng did not find any wireless interfaces')
 [!]  Exception: airmon-ng did not find any wireless interfaces

 [!] Exiting

huitc@HuiTC716:~/wifite2$ sudo python2 Wifite.py
   .               .
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´


 [+] Checking airmon-ng...
 [!] airmon-ng did not find any wireless interfaces
 [!] Make sure your wireless device is connected
 [!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

 [!] Error: airmon-ng did not find any wireless interfaces

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/huitc/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/home/huitc/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/home/huitc/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/home/huitc/wifite2/wifite/tools/airmon.py", line 299, in ask
 [!]        raise Exception('airmon-ng did not find any wireless interfaces')
 [!]  Exception: airmon-ng did not find any wireless interfaces

 [!] Exiting
```

**Comment by 687766616e** [comment]
```
$ uname -a
Linux HuiTC716 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 GNU/Linux
```
windows 10 pro wsl kali

**Comment by 687766616e** [comment]
```
$ sudo ./runtests.sh
test_airmon_start (test_Airmon.TestAirmon) ... ok
test_airodump_weird_characters (test_Airodump.TestAirodump) ... ok
testAnalyze (test_Handshake.TestHandshake) ...  [+] Discovered essid "Test Router Please Ignore"
 [+]   tshark: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a
 [+]    pyrit: .cap file contains a valid handshake for a4:2b:8c:16:6b:3a (Test Router Please Ignore)
 [!] aircrack: .cap file does not contain a valid handshake
ok
testHandshakeAircrack (test_Handshake.TestHandshake) ... FAIL
testHandshakeCowpatty (test_Handshake.TestHandshake) ... skipped 'cowpatty is missing'
testHandshakePyrit (test_Handshake.TestHandshake) ... ok
testHandshakeTshark (test_Handshake.TestHandshake) ... ok
testTargetClients (test_Target.TestTarget)
Asserts target parsing captures clients properly ... ok
testTargetParsing (test_Target.TestTarget)
Asserts target parsing finds targets ... ok

======================================================================
FAIL: testHandshakeAircrack (test_Handshake.TestHandshake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/huitc/wifite2/tests/test_Handshake.py", line 53, in testHandshakeAircrack
    assert(len(hs.aircrack_handshakes()) > 0)
AssertionError

----------------------------------------------------------------------
Ran 9 tests in 18.077s

FAILED (failures=1, skipped=1)
```

**Comment by RaduNico** [comment]
So if I am getting this right you are running kali in a virtualized environment in windows 10. I've tried running wifite2 in a virtual machine before and had limited success even though I granted the guest system direct device permissions on the wifi dongle. Looking though the wifite code your error simply means there is no available wifi interface that airmon can find.

Your best chance would be to run kali from a bootable stick/dual boot with a linux.

**Comment by ItsIgnacioPortal** [comment]
**Close this issue...**
