### ISSUE TITLE
some problem (bug?)

### ISSUE THREAD

**Issue by 687766616e** [derv82/wifite2#211]
`win10 pro`   `vbox` `kali for vbox 64bit`
`Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux`

```
root@kali:~/Desktop/hcxdumptool# wifite
   .               .    
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´    

 [!] Conflicting processes: NetworkManager (PID 484), dhclient (PID 572), wpa_supplicant (PID 874)
 [!] If you have problems: kill -9 PID or re-run wifite with --kill)

    Interface   PHY   Driver              Chipset                                                       
-----------------------------------------------------------------------
 1. wlan0       phy1  8812au                                            

 [+] enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find None with Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/tools/airmon.py", line 195, in start
 [!]        raise Exception('Cannot find %s with Mode:Monitor' % enabled_iface)
 [!]  Exception: Cannot find None with Mode:Monitor

 [!] Exiting
```

```
 [+] XXXXX-A60369 (21db) WPA Handshake capture: Waiting for target to appear...                          
 [!] Error: Target did not appear after 60 seconds, stopping

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/attack/all.py", line 86, in attack_single
 [!]        result = attack.run()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/attack/wpa.py", line 42, in run
 [!]        handshake = self.capture_handshake()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/attack/wpa.py", line 94, in capture_handshake
 [!]        airodump_target = self.wait_for_target(airodump)
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/model/attack.py", line 24, in wait_for_target
 [!]        raise Exception('Target did not appear after %d seconds, stopping' % Attack.target_wait)
 [!]  Exception: Target did not appear after 60 seconds, stopping

 [+] (6/16) Starting attacks against XX:XX:XX:A6:03:6A (XXXXX-XXXXXX-Guest)
```

**Comment by Czechball** [comment]
You can't run Wifite in Virtual box in Windows. Windows has wireless drivers security restrictions that prevent WiFi devices from entering monitor mode or injecting packets.

**Comment by 687766616e** [comment]
what should I do to make it run?? ^^''

**Comment by 687766616e** [comment]
```
root@kali:~/Desktop# wifite
   .               .    
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´    

 [!] Conflicting processes: NetworkManager (PID 487), dhclient (PID 576), wpa_supplicant (PID 877)
 [!] If you have problems: kill -9 PID or re-run wifite with --kill)

    Interface   PHY   Driver              Chipset                                                       
-----------------------------------------------------------------------
 1. wlan0       phy1  8812au                                            

 [+] enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find None with Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/usr/local/lib/python2.7/dist-packages/wifite/tools/airmon.py", line 195, in start
 [!]        raise Exception('Cannot find %s with Mode:Monitor' % enabled_iface)
 [!]  Exception: Cannot find None with Mode:Monitor

 [!] Exiting
```

```
root@kali:~/Desktop# wifite --kill
   .               .    
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´    

 [+] option: kill conflicting processes enabled
 [!] Killing 3 conflicting processes
 [!] stopping network-manager (service network-manager stop)
 [!] Terminating conflicting process dhclient (PID 576)
 [!] Terminating conflicting process wpa_supplicant (PID 877)

 [+] Using wlan0 already in monitor mode                                                                

   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT                                       
   ---  -------------------------  ---  ----  -----  ----  ------
     1                       rut    10   WPA   65db   yes    4                                          
     2                   rtyING    11   WPA   31db    no    1                                          
     3                        YY     5   WPA   29db   yes    1                                          
     4                   JOwerYC    11   WPA   22db   yes    1                                          
     5                  wer05     4   WPA   18db   yes    1                                          
     6                  yrdy*    6   WPA   17db   yes    1                                          
 [+] select target(s) (1-6) separated by commas, dashes or all:      
```

**Comment by Czechball** [comment]
Nothing. You just can't run it under Windows kernel. You need a Linux kernel with compatible firmware and wireless adapters.

**Comment by jcameron-oasis** [comment]
I've ran wifite successfully several times in a virtual machine on a Windows 10 laptop.  But it doesn't always work.  Is this security thing the cause of my intermittent problems?

**Comment by lovermann** [comment]
> I've ran wifite successfully several times in a virtual machine on a Windows 10 laptop. But it doesn't always work. Is this security thing the cause of my intermittent problems?

It's very interesting, how did you do it, because for example in VirtualBox linux system doesn't have direct access to wireless adapter (system "sees" only ethernet internet connection).

**Comment by jcameron-oasis** [comment]
> > I've ran wifite successfully several times in a virtual machine on a Windows 10 laptop. But it doesn't always work. Is this security thing the cause of my intermittent problems?
> 
> It's very interesting, how did you do it, because for example in VirtualBox linux system doesn't have direct access to wireless adapter (system "sees" only ethernet internet connection).

Maybe I got lucky.  But I bought 3 different usb wifi adapters, all of which were suppose to support monitor mode according to an article.  Only one of them actually did or at least could be put into monitor mode.  Using a kali install in virtual box on a windows 10 host.  I am very amateur so I didn't do anything special. 
 It doesn't always work though.  I have to set the virtual machine back to a snapshot that I made. 
 After I start wifite, it seems like it is just hung up or not going to do anything; I just walk away and come back half an hour later and it will have all the available "targets". 

Also my Mint virtual box does use the wireless, but I think that I bridged it somehow to the ethernet.  Can't tell you specifically what I did there cause I followed a bunch of google forum stuff and gave up after several different hour long attempts.  Then one day a few weeks later I noticed that I had internet even though I had not plugged in my ethernet cable.

Ironically I cannot get my windows 7 virtual machine on the same computer to connect through wifi.  My boss(also a github user but can't find his account right now), our IT guy, and myself have spent hours and hours trying to get it to work over the last  year with windows 7 and no success.  I have to use an adapter for that one as well.

This is the usb wifi adapter
https://www.amazon.com/Sabrent-NT-WGHU-Long-Rang-Wardriving-Extension/dp/B003EVO9U4/ref=sr_1_1?ie=UTF8&qid=1545062656&sr=8-1&keywords=Realtek+8187L

I changed the antennae to this one, don't know if that matters cause I changed the antennae before I was using a virtual machine.  Started all this with an rpi but I have way more success in a virtual machine; pains me to say cause I am a huge rpi fan.
https://www.amazon.com/gp/product/B000SEQGT2/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

**Comment by Van-Quisher** [comment]
im having the same problem. im using a usb wifi adapter for my pc. its tp-link TL-WN823N. Please help. TIA

**Comment by jcameron-oasis** [comment]
Which problem? You can't activate monitor mode or what you are doing only works sometimes?
