### ISSUE TITLE
[WinError2] The System cannot find the file specified

### ISSUE THREAD

**Issue by Dmartin42** [derv82/wifite2#245]
vvvvvvvvvvvv  TRACEBACK vvvvvvvvvvvvv

C:\Users\dmart\wifite2>wifite.py
 [32m  .     [37m[2m     [0m[32m     .    [0m
 [32m.´  ·  .[37m[2m     [0m[32m.  ·  `.  [32mwifite [2m2.2.5[0m
 [32m:  :  : [37m[2m (¯) [0m[32m :  :  :  [0m[2mautomated wireless auditor[0m
 [32m`.  ·  `[37m[2m /¯\ [0m[32m´  ·  .´  [36m[2mhttps://github.com/derv82/wifite2[0m
 [32m  `     [37m[2m/¯¯¯\[0m[32m     ´    [0m

 [WinError 2] The system cannot find the file specified

 Full stack trace below

   Traceback (most recent call last):
 File "C:\Users\dmart\wifite2\wifite\__main__.py", line 111, in entry_point
     wifite.start()
File "C:\Users\dmart\wifite2\wifite\__main__.py", line 71, in start
       Configuration.get_monitor_mode_interface()
 File "C:\Users\dmart\wifite2\wifite\config.py", line 132, in get_monitor_mode_interface
       cls.interface = Airmon.ask()
 File "C:\Users\dmart\wifite2\wifite\tools\airmon.py", line 278, in ask
     Airmon.terminate_conflicting_processes()
File "C:\Users\dmart\wifite2\wifite\tools\airmon.py", line 327, in terminate_conflicting_processes
      airmon_output = Process(['airmon-ng', 'check']).stdout()
File "C:\Users\dmart\wifite2\wifite\util\process.py", line 89, in __init__
   self.pid = Popen(command, stdout=sout, stderr=serr, stdin=stdin, cwd=cwd, bufsize=bufsize)
File "C:\Users\dmart\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
       restore_signals, start_new_session)
File "C:\Users\dmart\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
     startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

  Exiting
-----------------------

1) How do I fix?
2) What file is it talking about? (I have aircrack-ng installed)

**Comment by Czechball** [comment]
Wifite is not supported on Windows.

**Comment by lovermann** [comment]
> Wifite is not supported on Windows.
You're right, but this error happens in linux as well.
