### ISSUE TITLE
Major issue with VirtualBox and Alfa AWUS036ACH

### ISSUE THREAD

**Issue by makeenology** [derv82/wifite2#259]
I keep geting this output when starting wifite. I tried all different drivers for this card but no luck. iwconfig shows that this card is in monitor mode:

wlan1     IEEE 802.11b  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency:2.457 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=-100 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

However, this is what I get when I start wifite:

1. wlan1       phy1  88XXau              Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter

 [+] enabling monitor mode on wlan1... failed
failed

 [!] Error: Cannot find any interfaces in monitor mode
                                                                                                    
 [!] Full stack trace below                                                                         
                                                                                                    
 [!]    Traceback (most recent call last):                                                          
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 98, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 51, in start                 
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/lib/python3/dist-packages/wifite/config.py", line 152, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 332, in ask              
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 203, in start            
 [!]        raise Exception('Cannot find any interfaces in monitor mode')
 [!]  Exception: Cannot find any interfaces in monitor mode                                         
                                                                                                    
 [!] Exiting

**Comment by Abraxas333** [comment]
This is a duplicate of #86. I have the same problem with the same adapter but so far there is no solution available.

**Comment by makeenology** [comment]
I actually found a solution for it last night, even though it is pretty weird. So I downloaded and installed airgeddon, and then install all the required tools for airgeddon. Then I ran it, put the card in monitor mode, and then opened a new terminal and ran wifite, and then it worked. However, now I am having problems with airgeddon not working with WPS monitoring.
