### ISSUE TITLE
Exception: airmon-ng did not find any wireless interfaces

### ISSUE THREAD

**Issue by SanskarP** [derv82/wifite2#307]
I am new to Kali Linux and I have tried every method I know but every time I start up Wifite, this is the message that comes up, "Exception: airmon-ng did not find any wireless interfaces". 

This the output after running Wifite:

   .               .
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´

 [+] Checking airmon-ng...
 [!] airmon-ng did not find any wireless interfaces
 [!] Make sure your wireless device is connected
 [!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

 [!] Error: airmon-ng did not find any wireless interfaces

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/ /wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/home/ /wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/home/ /wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/home/ /wifite2/wifite/tools/airmon.py", line 299, in ask
 [!]        raise Exception('airmon-ng did not find any wireless interfaces')
 [!]  Exception: airmon-ng did not find any wireless interfaces

 [!] Exiting

Anyone have any suggestions on how to fix this?

**Comment by aayushh5419** [comment]
i am also facing th same issue can anyone help

**Comment by player66tech** [comment]
help me please
