### ISSUE TITLE
Fake auth Exceptions

### ISSUE THREAD

**Issue by GMTSE** [derv82/wifite2#311]
```
# wifite -version
...  wifite2 2.5.2
```

```
# wifite -i wlx000f0032e9c8 -wep --require-fakeauth
[+] attempting fake-authentication with xxxxxxx... failed
 [!] Error: Fake-authenticate did not complete within 5 seconds
 [!] Full stack trace below
 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 67, in run
 [!]        if self.fake_auth():
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 342, in fake_auth
 [!]        raise Exception(
 [!]  Exception: Fake-authenticate did not complete within 5 seconds
```
Happens with any target, so I think the problem is a more general Exception...

More detailed error:
```
[+] select target(s) (1-4) separated by commas, dashes or all: 2,3,4                                                                                                                                                                        

 [+] (1/3) Starting attacks against 68:A3:78:0C:B5:E9 (freebox_CJUQSJ)

 [?]  Executing: airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv
 [+] attempting fake-authentication with 68:A3:78:0C:B5:E9...
 [?]  Executing: aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8

 [?]  sending interrupt to PID 417244 (aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8)
 failed

 [?]  sending interrupt to PID 417235 (airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv)

 [?]  Waited > 2.00 seconds for process to die, killing it

 [!] Error: Fake-authenticate did not complete within 5 seconds

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 67, in run
 [!]        if self.fake_auth():
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 342, in fake_auth
 [!]        raise Exception(
 [!]  Exception: Fake-authenticate did not complete within 5 seconds

 [?]  Executing: airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv

 [?]  sending interrupt to PID 417235 (airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv)

 [?]  Waited > 2.00 seconds for process to die, killing it
 [+] attempting fake-authentication with 68:A3:78:0C:B5:E9...
 [?]  Executing: aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8

 [?]  sending interrupt to PID 417267 (aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8)
 failed

 [?]  sending interrupt to PID 417257 (airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv)

 [?]  Waited > 2.00 seconds for process to die, killing it

 [!] Error: Fake-authenticate did not complete within 5 seconds

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 67, in run
 [!]        if self.fake_auth():
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 342, in fake_auth
 [!]        raise Exception(
 [!]  Exception: Fake-authenticate did not complete within 5 seconds

 [?]  Executing: airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv

 [?]  sending interrupt to PID 417257 (airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv)

 [?]  Waited > 2.00 seconds for process to die, killing it
 [+] attempting fake-authentication with 68:A3:78:0C:B5:E9...
 [?]  Executing: aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8

 [?]  sending interrupt to PID 417300 (aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8)
 failed

 [?]  sending interrupt to PID 417281 (airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv)

 [?]  Waited > 2.00 seconds for process to die, killing it

 [!] Error: Fake-authenticate did not complete within 5 seconds

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 67, in run
 [!]        if self.fake_auth():
 [!]    File "/usr/lib/python3/dist-packages/wifite/attack/wep.py", line 342, in fake_auth
 [!]        raise Exception(
 [!]  Exception: Fake-authenticate did not complete within 5 seconds

 [?]  Executing: airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv

 [?]  sending interrupt to PID 417281 (airodump-ng wlx000f0032e9c8 -a -w /tmp/wifiteijx8rxfp/wep --write-interval 1 -c 11 --wps --bssid 68:A3:78:0C:B5:E9 --output-format ivs,csv)
 [+] attempting fake-authentication with 68:A3:78:0C:B5:E9...
 [?]  Executing: aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8

 [?]  sending interrupt to PID 417318 (aireplay-ng -1 0 -a 68:A3:78:0C:B5:E9 -T 5 -e freebox_CJUQSJ wlx000f0032e9c8)
 failed

```

**Comment by liar666** [comment]
Hi,

Any news about this? I'm having the same problem.

- I've downladed github source code for wifite2 => same error
- I've checked "Required Tools" versions (mainly aircrack-ng) and I'm having 1.6 which is the latest according to their website...
- I've found a Kali.iso of version 2020.03 on my HD => no problem, but it's using wifite 2.5.5, unfortunately, I don't have enough bandwith to download Kali 2020.04

Are we the only ones with this problem?!?!? Is there a solution?

**Comment by liar666** [comment]
News: I tried with kali 2020.4 => same problem...

So there's a confirmation there's a bug.

If someone could have a look at the problem....
