### ISSUE TITLE
Fix wifite in kalinethunter(rooted devices)

### ISSUE THREAD

**Issue by moner124** [derv82/wifite2#382]
.
 .´  ·  .     .  ·  `.  wifite2 2.5.8
 :  :  :  (¯)  :  :  :  a wireless auditor by derv82
 `.  ·  ` /¯\ ´  ·  .´  maintained by kimocoder
   `     /¯¯¯\     ´    https://github.com/kimocoder/wifite2

 [!] Warning: Recommended app bully was not found. install @ https://github.com/aanarchyy/bully
 [!] Warning: Recommended app pyrit was not found. install @ https://github.com/JPaulMora/Pyrit/wiki
 [!] Warning: Recommended app hashcat was not found. install @ https://hashcat.net/hashcat/
 [!] Warning: Recommended app hcxdumptool was not found. install @ apt install hcxdumptool
 [!] Warning: Recommended app hcxpcapngtool was not found. install @ apt install hcxtools

                                                                                                    Interface   PHY   Driver              Chipset
-----------------------------------------------------------------------
 1. wlan0       null  ??????              non-mac80211 device? (report this!)

 [+] enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find any interfaces in monitor mode

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 97, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 51, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/lib/python3/dist-packages/wifite/config.py", line 167, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 333, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 204, in start
 [!]        raise Exception('Cannot find any interfaces in monitor mode')
 [!]  Exception: Cannot find any interfaces in monitor mode

 [!] Exiting

**Comment by kimocoder** [comment]
And may I ask what kinda device you trying to use? Doesnt look much supported..

I've used it on NetHunter for 4-5 years now, if not more  👍
