### ISSUE TITLE
wlan0 null ??????

### ISSUE THREAD

**Issue by zxphyrx** [derv82/wifite2#399]
```
[!] Warning: Recommended app reaver was not found. install @ https://github.com/t6x/reaver-wps-fork-t6x
 [!] Warning: Recommended app bully was not found. install @ https://github.com/aanarchyy/bully
 [!] Warning: Recommended app pyrit was not found. install @ https://github.com/JPaulMora/Pyrit/wiki
 [!] Warning: Recommended app tshark was not found. install @ apt-get install wireshark                    [!] Warning: Recommended app hashcat was not found. install @ https://hashcat.net/hashcat/                [!] Warning: Recommended app hcxdumptool was not found. install @ https://github.com/ZerBea/hcxdumptool   [!] Warning: Recommended app hcxpcaptool was not found. install @ https://github.com/ZerBea/hcxtools     
    Interface   PHY   Driver              Chipset    
-----------------------------------------------------------------------
 1. wlan0       null  ??????              non-mac80211 device? (report this!)
                                                      [+] enabling monitor mode on wlan0... failed
failed                                               
 [!] Error: Cannot find any interfaces in Mode:Monitor
                                                      [!] Full stack trace below
                                                      [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()                            [!]    File "/root/wifite2/wifite/__main__.py", line 53, in start                                         [!]        Configuration.get_monitor_mode_interface()                                                     [!]    File "/root/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface                     [!]        cls.interface = Airmon.ask()
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)     [!]    File "/root/wifite2/wifite/tools/airmon.py", line 190, in start                                    [!]        raise Exception('Cannot find any interfaces in Mode:Monitor')                                  [!]  Exception: Cannot find any interfaces in Mode:Monitor                                               
 [!] Exiting
````

Running in Termux

**Comment by a047b19** [comment]
1. wlan0       null  ??????              non-mac80211 device? (report this!)

 [+] enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find any interfaces in Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/root/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/root/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 190, in start
 [!]        raise Exception('Cannot find any interfaces in Mode:Monitor')
 [!]  Exception: Cannot find any interfaces in Mode:Monitor

 [!] Exiting
