### ISSUE TITLE
Cant enable monitor mode Cannot find None with Mode:Monitor

### ISSUE THREAD

**Issue by ririko5834** [derv82/wifite2#424]
Hi, I get this error with both --kill option and without it too.

```
root@pi3lts:~/wifite2# python3 Wifite.py --kill
   .               .
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´

 [+] option: kill conflicting processes enabled
 [!] Warning: Recommended app pyrit was not found. install @ https://github.com/JPaulMora/Pyrit/wiki
 [!] Killing 2 conflicting processes
 [!] Terminating conflicting process wpa_supplicant (PID 6307)
 [!] stopping network-manager (service network-manager stop)

    Interface   PHY   Driver              Chipset
-----------------------------------------------------------------------
 1. wlan0       phy0  unisoc_wifi         Not pci, usb, or sdio
 2. wlx54af97ec1a43phy1  88XXau              TP-Link AC600 wireless Realtek RTL8811AU [Archer T2U Nano]

 [+] Select wireless interface (1-2): 2
 [+] enabling monitor mode on wlx54af97ec1a43... failed
failed

 [!] Error: Cannot find None with Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/root/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/root/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 195, in start
 [!]        raise Exception('Cannot find %s with Mode:Monitor' % enabled_iface)
 [!]  Exception: Cannot find None with Mode:Monitor

 [!] Exiting

 [!] You can restart NetworkManager when finished (service network-manager start)


```

**Comment by usaflees** [comment]
You need to use the other card, I’ve never laid on a card named what you have on that 2nd line

**Comment by bapriddy** [comment]
Okay I checked at Ask.Ubuntu and they say it has monitor mode.
