### ISSUE TITLE
ModuleNotFoundError: No module named 'wifite.wifite'

### ISSUE THREAD

**Issue by savioazure** [derv82/wifite2#434]
└─# wifite
Traceback (most recent call last):
  File "/usr/sbin/wifite", line 33, in <module>
    sys.exit(load_entry_point('wifite==2.2.5', 'console_scripts', 'wifite')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sbin/wifite", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wifite.wifite'

**Comment by exeKatana** [comment]
> └─# wifite Traceback (most recent call last): File "/usr/sbin/wifite", line 33, in sys.exit(load_entry_point('wifite==2.2.5', 'console_scripts', 'wifite')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/sbin/wifite", line 25, in importlib_load_entry_point return next(matches).load() ^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/importlib/metadata/**init**.py", line 202, in load module = import_module(match.group('module')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1206, in _gcd_import File "", line 1178, in _find_and_load File "", line 1142, in _find_and_load_unlocked ModuleNotFoundError: No module named 'wifite.wifite'

did u solve it?

**Comment by Houdabel05** [comment]
does anyone know how to solve this problem ?

**Comment by exeKatana** [comment]
> does anyone know how to solve this problem ?

still searching..

**Comment by Cetttok** [comment]
2026... install via package manager (ex pacman) or if you wont run from github.....


need install via setup.py (like in the readme) and check if /usr/lib/python3.14/site-packages/wifite exist and contains files like that (python3.14 may be another version)  ls /usr/lib/python3.14/site-packages/wifite
args.py  config.py    __main__.py  __pycache__  util
attack   __init__.py  model        tools 
(if site-packages/wifite not exsist and not contain files you need to run via root in main repo directory pip install --break-system-packages . ) 

and make some changes in /usr/bin/wifite:
replace 'from wifite.wifite import entry_point' 
to 'from wifite.__main__ import entry_point'
