### ISSUE TITLE
 [!]    File "./Wifite.py", line 201, in <module>

### ISSUE THREAD

**Issue by 0xakrem** [derv82/wifite2#45]
[+] option: scanning for targets on channel 7

 [!] Error: [Errno 2] No such file or directory

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 201, in <module>
 [!]        w.main()
 [!]    File "./Wifite.py", line 38, in main
 [!]        Configuration.get_interface()
 [!]    File "/home/akrem/pen/wifite2/py/Configuration.py", line 106, in get_interface
 [!]        Configuration.interface = Airmon.ask()
 [!]    File "/home/akrem/pen/wifite2/py/Airmon.py", line 173, in ask
 [!]        Airmon.terminate_conflicting_processes()
 [!]    File "/home/akrem/pen/wifite2/py/Airmon.py", line 235, in terminate_conflicting_processes
 [!]        out = Process(['airmon-ng', 'check']).stdout()
 [!]    File "/home/akrem/pen/wifite2/py/Process.py", line 81, in __init__
 [!]        self.pid = Popen(command, stdout=sout, stderr=serr, cwd=cwd, bufsize=bufsize)
 [!]    File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
 [!]        errread, errwrite)
 [!]    File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
 [!]        raise child_exception
 [!]    OSError: [Errno 2] No such file or directory

 [!] Exiting

Exception AttributeError: "'Process' object has no attribute 'pid'" in <bound method Process.__del__ of <py.Process.Process object at 0x7fe3b6bb1350>> ignored

**Comment by ritiek** [comment]
Are you sure you have the `aircrack-ng` package installed?

**Comment by MisterBianco** [comment]
What OS are you using?

_Sent from my Samsung SM-N900T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kimocoder** [comment]
I remember this "crash" I think.. was it when there where no adapters plugged or something? 

Anyway, your issue report is missing more information. Please give more details, which command was used/were the error occoured so others may reproduce it for a potiensial fix for it.

**Comment by trickpattyFH20** [comment]
I'm getting the same error.
I do have aircrack-ng installed.
running on OSX 10.12.6
<details>
<summary>stack trace (click to expand)</summary>
 [+] option: targeting WEP-encrypted networks

 [!] Error: [Errno 2] No such file or directory

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 201, in <module>
 [!]        w.main()
 [!]    File "./Wifite.py", line 38, in main
 [!]        Configuration.get_interface()
 [!]    File "/Users/patricklawler/Documents/projects/wifite2/py/Configuration.py", line 106, in get_interface
 [!]        Configuration.interface = Airmon.ask()
 [!]    File "/Users/patricklawler/Documents/projects/wifite2/py/Airmon.py", line 173, in ask
 [!]        Airmon.terminate_conflicting_processes()
 [!]    File "/Users/patricklawler/Documents/projects/wifite2/py/Airmon.py", line 235, in terminate_conflicting_processes
 [!]        out = Process(['airmon-ng', 'check']).stdout()
 [!]    File "/Users/patricklawler/Documents/projects/wifite2/py/Process.py", line 81, in __init__
 [!]        self.pid = Popen(command, stdout=sout, stderr=serr, cwd=cwd, bufsize=bufsize)
 [!]    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
 [!]        errread, errwrite)
 [!]    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
 [!]        raise child_exception
 [!]    OSError: [Errno 2] No such file or directory

 [!] Exiting

Exception AttributeError: "'Process' object has no attribute 'pid'" in <bound method Process.__del__ of <py.Process.Process object at 0x10ccf0650>> ignored
</details>

**Comment by kimocoder** [comment]
Ok. im on my home from holidays now, will take a look tomorrow

**Comment by MisterBianco** [comment]
My guess is subprocess is using a sys call that only works on Linux.

Because this tool is only meant to run on Kali Linux.

**Comment by ritiek** [comment]
I just tested on my friend's Mac.

It seems like `airmon-ng` is not available for OSX (although other tools like `airodump-ng`, `aireplay-ng`, `aircrack-ng` are available). I tried installing it with both Brew and MacPorts but no luck. Someone mentioned it in this [forum post](https://forum.aircrack-ng.org/index.php/topic,1460.0.html) as well.

Unless there is another way to put a WiFi interface into monitor mode, Mac users are going to be out of luck.

**Comment by kimocoder** [comment]
Do it manually with:

ifconfig <adapter> down
iwconfig <adapter> mode monitor
ifconfig <adapter> up

**Comment by kimocoder** [comment]
Btw!

The "[!] File "./Wifite.py", line 201, in <module>" error displays when there are NO ADAPTERS FOUND. Just tested this on my setup and got the same output as mentioned.

**Comment by MisterBianco** [comment]
Try going to my profile and downloading my boopsuite repo and using 

./boop.py -i wlan1 

and tell me if it works on mac

**Comment by MisterBianco** [comment]
@kimocoder 

If you have a Mac will you test my tool and see if it works? I'm curious

**Comment by ritiek** [comment]
@kimocoder `iwconfig` is not available on Mac.
