### ISSUE TITLE
Cannot find any interfaces in monitor mode ( in wifite using ubuntu for root( in root))

### ISSUE THREAD

**Issue by Youaymo** [derv82/wifite2#471]
Interface   PHY   Driver              Chipset                     
-----------------------------------------------------------------------
 1. wlan0       null  ??????              non-mac80211 device? (report this!)

 [+] enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find any interfaces in monitor mode

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 100, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 54, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/lib/python3/dist-packages/wifite/config.py", line 168, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 333, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 204, in start
 [!]        raise Exception('Cannot find any interfaces in monitor mode')
 [!]  Exception: Cannot find any interfaces in monitor mode

 [!] Exiting

root@localhost:~# wifite Configuration.get_monitor_mode_interface()
bash: syntax error near unexpected token `('
root@localhost:~# airodump-ng wlan1
Failed to connect to generic netlink.
socket(PF_PACKET) failed: Permission denied
Failed initializing wireless card(s): wlan1
root@localhost:~# airodump-ng wlan1
Failed to connect to generic netlink.
socket(PF_PACKET) failed: Permission denied
Failed initializing wireless card(s): wlan1
root@localhost:~# airodump-ng wlan1
Failed to connect to generic netlink.
socket(PF_PACKET) failed: Permission denied
Failed initializing wireless card(s): wlan1
root@localhost:~# sudo ifconfig wlanx down
wlanx: ERROR while getting interface flags: No such device
root@localhost:~# sudo ifconfig wlan1 down
wlan1: ERROR while getting interface flags: No such device
root@localhost:~#
![Screenshot_20240529-040533](https://github.com/derv82/wifite2/assets/109590790/4b99919e-d1e7-4d2b-810d-fc7b72090c25)

**Comment by obade7** [comment]
???
