### ISSUE TITLE
airmon-ng exception in the nethunter nexmon mode on a nexus5

### ISSUE THREAD

**Issue by intosec** [derv82/wifite2#50]
I'm trying to run wifi2 in the latest netunter on my nexus5 with it's own wireless chip, here is what i do:
```
source monstart-nh
python wifite2/Wifite.py
```
but i got this
```
 [!] Error: Expected 4, got 1 in ['Run it as root']

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "Wifite.py", line 201, in <module>
 [!]        w.main()
 [!]    File "Wifite.py", line 38, in main
 [!]        Configuration.get_interface()
 [!]    File "/root/wifite2/py/Configuration.py", line 106, in get_interface
 [!]        Configuration.interface = Airmon.ask()
 [!]    File "/root/wifite2/py/Airmon.py", line 186, in ask
 [!]        a = Airmon()
 [!]    File "/root/wifite2/py/Airmon.py", line 18, in __init__
 [!]        self.refresh()
 [!]    File "/root/wifite2/py/Airmon.py", line 22, in refresh
 [!]        self.interfaces = Airmon.get_interfaces()
 [!]    File "/root/wifite2/py/Airmon.py", line 56, in get_interfaces
 [!]        interfaces.append(Interface(fields))
 [!]    File "/root/wifite2/py/Interface.py", line 39, in __init__
 [!]        raise Exception("Expected 4, got %d in %s" % (len(fields), fields))
 [!]  Exception: Expected 4, got 1 in ['Run it as root']

 [!] Exiting
```
and i run airmon-ng, it returns this
```
####################################################
## nexmon ioctl hook active
## sa_family = ARPHRD_IEEE80211_RADIOTAP
## to change sa_family, set NEXMON_SA_FAMILY
## environment variable to ARPHRD_IEEE80211
####################################################
Run it as root####################################################
## nexmon ioctl hook active
## sa_family = ARPHRD_IEEE80211_RADIOTAP
## to change sa_family, set NEXMON_SA_FAMILY
## environment variable to ARPHRD_IEEE80211
####################################################
Run it as root
```
so, i think maybe it's because of the nexmon mode doesn't works fine with airmon-ng. But the old wifite works fine in this situation. I think we can add an option to force this script not to check airmon-ng to let it work.
>PS: sorry for my poor English.

**Comment by ritiek** [comment]
I think you probably need to somehow run it as root like it says.

**Comment by MisterBianco** [comment]
yeah its a permissions issue try putting sudo in front of the command
