### ISSUE TITLE
WPA cracking method "aircrack-ng" doesn't load dict properly

### ISSUE THREAD

**Issue by kimocoder** [derv82/wifite2#66]
when using the "aircrack-ng" method with dict "/usr/share/wordlists/fern-wifi/common.txt" wifite2 doesn't load the dict properly and the output will become

` [!] Failed to crack handshake: common.txt did not contain password`

even though the file (checked manually) actually contains passwords.
don't know if it's the loading or parsing (processing) that fails.

**THIS IS WRONG. IT WORKS AS IT SHOULD. LOOK AT ISSUE (STACK TRACE) BELOW INSTEAD**

**Comment by kimocoder** [comment]
Another "bug" is when i provide the actual password into the "common.txt" this happens:
* NOTE: Most important information remains hidden for obvious reasons.. like AP name/MAC and pass
----------------------------------------------------------------------------------------------------------------------------------
 [+] enabling monitor mode on wlan0... enabled wlan0mon

   NUM                     ESSID   CH  ENCR  POWER  WPS?  CLIENT                                                                                                                              
   --- -------------------------  ---  ----  -----  ----  ------
     1                    ******    1   WPA   56db    no                                                                                                                                      
     2               Secret AP    1   WPA   47db    no    3                                                                                                                                 
     3              Secret AP   1   WPA   47db    no                                                                                                                                      
     4                    ******    6   WPA   38db    no                                                                                                                                      
     5              Secret AP    6   WPA   34db    no                                                                                                                                      
     6              Secret AP    6   WPA   34db    no                                                                                                                                      
     7              REMOTE58kpys    3   WPA   25db    no                                                                                                                                      
     8                    ******  11   WPA   21db    no                                                                                                                                      
     9               Secret AP   11   WPA   18db    no                                                                                                                                      
 [+] select target(s) (1-9) separated by commas, dashes or all: 2                                                                                                                             

 [+] (1/1) starting attacks against 9x:xx:12:xC:77:xx (Secret AP)
 [+] found existing handshake for Secret AP                                                                                                                                                 
 [+] from hs/handshake_essid_macadr_2018-02-28T12-23-30.cap

 [+] analysis of captured handshake file:
 [+]   tshark: .cap file contains a valid handshake for 9x:xx:12:xC:77:xx
 [!]    pyrit: .cap file does not contain a valid handshake
 [+] cowpatty: .cap file contains a valid handshake for (Tyrili Elev)
 [+] aircrack: .cap file contains a valid handshake for 9x:xx:12:xC:77:xx

 [+] Cracking WPA Handshake: Using aircrack-ng via common.txt wordlist
 [+] Cracking WPA Handshake: 5.08% ETA: 0s @ 1316.2kps (current key: )                                                                                                                        
 [+] Cracked WPA Handshake PSK: **************


 [!] Error: global name 'bssid' is not defined

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 137, in run
 [!]        attack.run()
 [!]    File "/root/wifite2/py/AttackWPA.py", line 57, in run
 [!]        self.crack_result = CrackResultWPA(bssid, essid, handshake.capfile, key)
 [!]    NameError: global name 'bssid' is not defined
 [+] Finished attacking 1 target(s), exiting
 [!] disabling monitor mode on wlan0mon... disabled wlan0mon
 [!] putting interface wlan0 up... done
 [!] restarting NetworkManager... restarted
