### ISSUE TITLE
After successful handshake, i got this error (Version 2.1.0) on Kali

### ISSUE THREAD

**Issue by iqzer0** [derv82/wifite2#95]
[+] successfully captured handshake

 [!] Error: expected string or buffer

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 176, in run
 [!]        attack.run()
 [!]    File "/usr/share/wifite/wifite/attack/wpa.py", line 41, in run
 [!]        handshake = self.capture_handshake()
 [!]    File "/usr/share/wifite/wifite/attack/wpa.py", line 153, in capture_handshake
 [!]        self.save_handshake(handshake)
 [!]    File "/usr/share/wifite/wifite/attack/wpa.py", line 256, in save_handshake
 [!]        essid_safe = re.sub('[^a-zA-Z0-9]', '', handshake.essid)
 [!]    File "/usr/lib/python2.7/re.py", line 155, in sub
 [!]        return _compile(pattern, flags).sub(repl, string, count)
 [!]    TypeError: expected string or buffer

**Comment by derv82** [comment]
Looks like you managed to capture a handshake without knowing the ESSID.

I'll try to reproduce & fix.

**Comment by deadport** [comment]
Ive got the same problem here and wifite definitly got the ESSID at first when I start looking for handshakes.

**Comment by stealthysquirrel** [comment]
im having exactly same problems......

**Comment by Lupingupta** [comment]
[+] successfully captured handshake [!] Error: expected string or buffer [!] Full stack trace below [!] Traceback (most recent call last): [!] File "/usr/share/wifite/wifite/wifite.py", line 176, in run [!] attack.run() [!] File "/usr/share/wifite/wifite/attack/wpa.py", line 41, in run [!] handshake = self.capture_handshake() [!] File "/usr/share/wifite/wifite/attack/wpa.py", line 153, in capture_handshake [!] self.save_handshake(handshake) [!] File "/usr/share/wifite/wifite/attack/wpa.py", line 256, in save_handshake [!] essid_safe = re.sub('[^a-zA-Z0-9]', '', handshake.essid) [!] File "/usr/lib/python2.7/re.py", line 155, in sub [!] return _compile(pattern, flags).sub(repl, string, count) [!] TypeError: expected string or buffer
